[build-system]
requires = [
    "setuptools>=61.0", 
    "wheel",
    "pandas", 
    "numpy",
    "scipy",
    "matplotlib",
    "scikit-learn"
    "jellyfish"]
build-backend = "setuptools.build_meta"
